Quests, Underworld achievements, Sanctum of Rebirth
source-chunk/chunk-picker-rs3 pull request #1
Opened 2024-08-24 21:24 UTC by SnowyToo

Also includes misc fixes to make the new and some old quests work properly

2024-08-25 05:36 UTC, ThaFrenchFry requested changes
Fix the roar and the extra space and you're golden

2024-08-25 05:36 UTC, ThaFrenchFry commented on rs3-chunkpicker-chunkinfo-export.json
> +				"Items": ["Ode of Awakening"],
Should be "Items": ["Roar of Awakening"]

2024-08-25 05:36 UTC, ThaFrenchFry commented on rs3-chunkpicker-chunkinfo-export.json
> +
typo I think?

2024-08-26 16:31 UTC, ThaFrenchFry approved these changes

2024-08-27 02:34 UTC, Connor3455 approved these changes

2024-08-27 12:40 UTC, source-chunk commented
Implemented via #2

2024-08-27 12:40 UTC, closed without merging