Ability/Prayer Tasks & DnD Skilling
source-chunk/chunk-picker-rs3 pull request #13
Opened 2024-11-14 22:04 UTC by SnowyToo

- Rule: "Unlock reward abilities" (vanilla default)
  - DOES include Necormancy incantation (singular, only Bone Lord is a reward atm)
  - DOES NOT include Necromancy abilties from the talent tree (less "reward", more "core skill progression")
  - Subrule: "Include sigil abilities" (extreme default)
- Rule: "Unlock reward prayers" (vanilla default)
  - DOES include post-quest rewards
  - DOES include the locked Necromancy prayers/curses

Also fixed everything that's been flagged since the previous update, including filling out DnD Skilling (for that one Menaphos guy).

2024-11-14 23:57 UTC, source-chunk requested changes

2024-11-14 23:57 UTC, source-chunk commented on index.js
> +        "Prayers": true,
Remove trailing comma here, to keep with style for rest of this object

2024-11-15 14:01 UTC, Connor3455 approved these changes

2024-11-22 23:45 UTC, Connor3455 approved these changes

2024-11-23 00:08 UTC, ThaFrenchFry approved these changes

2024-11-23 16:42 UTC, source-chunk approved these changes

2024-11-23 18:08 UTC, merged